
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./backend/.env        # aquí defines MONGO_URI, JWT_SECRET…
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:80"
    environment:
      # Apunta al backend desde el navegador:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data:
